import Navbar from '@/components/Navbar';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <div className="max-w-4xl mx-auto px-6 py-16 md:py-20">
        <div className="mb-10">
          <h1 className="text-4xl font-semibold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-lg text-muted-foreground">Last updated: June 14, 2026 — Version 1.1</p>
        </div>

        <div className="legal-content">
          <p>
            These Terms of Service ("Terms") govern your access to and use of MyTech-Fix (the "Service"), operated by MyTech-Fix LLC, a limited liability company registered in the State of [State], USA ("Company," "we," "us," or "our"). By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>

          <h2>1. Description of Service</h2>
          <p>
            MyTech-Fix provides an AI-powered platform that offers step-by-step technical support and troubleshooting assistance for hardware and software issues, including but not limited to networking, computers, smart home devices, printers, and productivity tools.
          </p>
          <p>
            <strong>The Service does not provide professional IT consulting, managed IT services, cybersecurity incident response, legal advice, or any other professional services.</strong> Responses generated by the Service are general educational information only. For critical systems, active security incidents, or business-critical infrastructure, always engage a qualified IT professional.
          </p>

          <h2>2. Eligibility and Accounts</h2>
          <p>
            You must be at least 16 years old to use the Service. If you are located in a jurisdiction where the minimum age for data processing consent is higher (e.g., certain EU member states), you must meet that higher age requirement. By using the Service, you represent that you meet the applicable age requirement.
          </p>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately at <a href="mailto:admin@mytech-fix.com">admin@mytech-fix.com</a> if you suspect unauthorized use of your account.
          </p>
          <p>
            Business accounts may include multiple users ("Team Members"). The account owner is solely responsible for the actions of all Team Members added to the account and agrees to indemnify MyTech-Fix LLC for any claims, damages, or expenses arising from Team Member misuse of the Service.
          </p>

          <h2>3. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any illegal purpose or in violation of any applicable laws or regulations</li>
            <li>Attempt to reverse engineer, decompile, or extract the underlying AI models or proprietary systems</li>
            <li>Upload malicious content, viruses, or content that infringes on the intellectual property or rights of others</li>
            <li>Share account credentials with unauthorized parties (except through official team seat features)</li>
            <li>Use the Service to generate content for spam, phishing, or deceptive practices</li>
            <li>Attempt to circumvent usage limits, billing systems, or access controls</li>
            <li>Scrape, crawl, or systematically extract data from the Service</li>
          </ul>

          <h2>4. AI-Generated Content and Limitations</h2>
          <p>
            MyTech-Fix uses artificial intelligence to provide suggestions and instructions, including general educational guidance on cybersecurity events. While we strive for accuracy, AI responses may contain errors, outdated information, or be inappropriate for your specific situation. The Service is not infallible and should be used as one input among many when making technical decisions.
          </p>
          <p>
            <strong>You acknowledge and agree that:</strong>
          </p>
          <ul>
            <li>AI-generated advice is not a substitute for professional technical support, managed IT services, or cybersecurity incident response</li>
            <li>For any active cybersecurity event or suspected breach, you must immediately contact qualified IT security professionals — the Service is not an incident response service</li>
            <li>You are solely responsible for evaluating and following any instructions provided by the Service</li>
            <li>MyTech-Fix LLC is not liable for any damage to devices, data loss, security breaches, business interruption, or other consequences resulting from your use of or reliance on the Service</li>
          </ul>

          <h2>5. Subscriptions, Billing, and Refunds</h2>
          <p>
            Paid plans are billed in advance on a recurring monthly or annual basis. You may cancel your subscription at any time through your Account settings or the Stripe customer portal. Upon cancellation, you will retain access to paid features until the end of your current billing period; your account will then revert to the free tier.
          </p>
          <p>
            <strong>Refund Policy:</strong> All fees are non-refundable except as required by applicable law. At our sole discretion, we may issue a refund within 7 days of a charge if you have not materially used the Service during that period. To request a refund, contact <a href="mailto:admin@mytech-fix.com">admin@mytech-fix.com</a> within 7 days of the charge.
          </p>
          <p>
            We reserve the right to change pricing with at least 30 days' advance notice sent to your registered email address. Price changes will not affect the current billing period and will take effect at the start of your next renewal period.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            The Service and all content, features, and functionality (including AI models, software, design, and trademarks) are owned by MyTech-Fix LLC or its licensors and are protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works without our express written permission.
          </p>
          <p>
            You retain ownership of the content you submit to the Service (including chat messages and uploaded images). By submitting content, you grant MyTech-Fix LLC a limited, non-exclusive, worldwide, royalty-free license to use, store, and process that content solely to provide the Service to you. We do not use your conversation content to train AI models without your explicit consent.
          </p>

          <h2>7. Data Retention and Deletion</h2>
          <p>
            We retain your personal data and chat history for as long as your account is active. Upon account deletion, your personal data (including chat sessions, diagnostic results, and profile information) is deleted within 30 business days, except where retention is required by applicable law, for fraud prevention, or to resolve outstanding billing disputes.
          </p>
          <p>
            You may request deletion of your account and associated data at any time through the Account Settings page or by contacting <a href="mailto:admin@mytech-fix.com">admin@mytech-fix.com</a>.
          </p>

          <h2>8. Termination</h2>
          <p>
            We may suspend or terminate your access to the Service for violation of these Terms or fraudulent activity, effective immediately and without prior notice. For other reasons, we will provide at least 30 days' written notice to your registered email address before termination, except where immediate action is required to protect the security or integrity of the Service or other users.
          </p>
          <p>
            You may delete your account at any time through the Account Settings page.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, MyTech-Fix LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenues, data, goodwill, or other intangible losses, arising out of or related to your use of the Service.
          </p>
          <p>
            In no event shall MyTech-Fix LLC's total aggregate liability to you for all claims arising out of or relating to these Terms or the Service exceed the greater of (a) the total amount you paid to MyTech-Fix LLC in the 12 months immediately preceding the claim or (b) fifty U.S. dollars ($50).
          </p>
          <p>
            Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages; in such jurisdictions, our liability shall be limited to the fullest extent permitted by law.
          </p>

          <h2>10. Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, secure, or error-free, or that AI responses will be accurate, complete, or suitable for your specific needs.
          </p>

          <h2>11. Dispute Resolution and Arbitration</h2>
          <p>
            <strong>Informal Resolution:</strong> Before initiating any formal proceeding, both parties agree to attempt to resolve disputes informally by contacting <a href="mailto:admin@mytech-fix.com">admin@mytech-fix.com</a> and negotiating in good faith for at least 30 days.
          </p>
          <p>
            <strong>Binding Arbitration:</strong> If informal resolution fails, any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved by binding individual arbitration administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules, rather than in court. You waive any right to a jury trial or to participate in a class action lawsuit or class-wide arbitration.
          </p>
          <p>
            <strong>Small Claims Exception:</strong> Either party may bring an individual claim in small claims court if the claim qualifies, in lieu of arbitration.
          </p>
          <p>
            <strong>Class Action Waiver:</strong> You agree that any claims must be brought in your individual capacity and not as a plaintiff or class member in any purported class or representative proceeding.
          </p>

          <h2>12. Force Majeure</h2>
          <p>
            MyTech-Fix LLC shall not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including but not limited to acts of God, internet or telecommunications outages, failures of third-party service providers (including Supabase, Stripe, xAI, OpenAI, or Cloudflare), cyberattacks, government actions, or other events outside our control.
          </p>

          <h2>13. Changes to Terms</h2>
          <p>
            We may modify these Terms at any time. For material changes, we will provide at least 14 days' advance notice by updating the "Last updated" date above, sending an email to your registered address, and/or displaying an in-app notification. Continued use of the Service after the effective date of changes constitutes your acceptance of the revised Terms. If you do not agree to the changes, you must stop using the Service and may delete your account before the effective date.
          </p>

          <h2>14. Governing Law and Venue</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the State of [State], USA, without regard to its conflict of law provisions. For any matters not subject to arbitration under Section 11, you consent to the exclusive jurisdiction of the state and federal courts located in [State].
          </p>

          <h2>15. General Provisions</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force. Our failure to enforce any right or provision does not constitute a waiver of that right. These Terms constitute the entire agreement between you and MyTech-Fix LLC regarding the Service and supersede all prior agreements.
          </p>

          <h2>16. Contact</h2>
          <p>For questions about these Terms, to submit legal notices, or to request data deletion, please contact us at:</p>
          <p>
            <strong>MyTech-Fix LLC</strong><br />
            [Business Address]<br />
            [City, State, ZIP]<br />
            Email: <a href="mailto:admin@mytech-fix.com">admin@mytech-fix.com</a>
          </p>

          <div className="legal-note">
            <strong className="text-foreground">Note:</strong> Bracketed items ([State], [Business Address], etc.) must be completed with your actual business details before publishing. Consult a qualified attorney licensed in your jurisdiction to review and finalize these terms before making the Service publicly available.
          </div>
        </div>
      </div>
    </div>
  );
}
